name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'menus/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'menus/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['lts/*', '*']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 1

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # 4.0.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #4.0.2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Packages Dependencies
        run: npm ci

      - name: Lint Source
        run: npm run lint --if-present

      - name: Build Source
        run: npm run build --if-present

      # - name: Run Tests
      #   run: npm run test --if-present
